config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  resources :positions
  resources :candidates
  resources :recruiters
  resources :meetings

  # recruiter to candidate route
  post '/candidates/:id/add-recruiter/:recruiter', to: 'candidates#add_recruiter'
  delete '/candidates/:id/add-recruiter', to: 'candidates#remove_recruiter'
  
  #login/logout routes
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/position.rb
class Position < ApplicationRecord
  has_many :position_skill, dependent: :delete_all
  has_many :skills, through: :position_skill
  has_many :candidates
  validates :title, presence: true, length: {minimum:3, maximum:50}
  validates :description, presence: true, length: {minimum:10, maximum:10000}
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
    before_action :set_position, only:[:edit,:update,:show,:destroy]
    before_action :require_user
    def index
        @positions = Position.all
    end
    def show
        
    end
    def new
        @position = Position.new
    end
    def create
        #just check if params are passing
        #render plain: params[:position].inspect

        @position = Position.new(position_params)
        if @position.save
            skill_params.each do |skill|
                @position.position_skill.create(skill_id:skill)
            end
            flash[:success] = "Positon was successfully created"
            redirect_to position_path(@position)    
        else
            render 'new'
        end
    end
    def edit
    end
    def update
        if @position.update(position_params)
            flash[:success] = "Position was successfully updated"
            redirect_to position_path(@position)    
        else
            render 'edit'
        end
        
    end
    def destroy
        @position.destroy
        flash[:danger] = "position was successfully deleted"
        redirect_to positions_path
        
    end

    private
    def set_position
        @position = Position.find(params[:id])
    end
    def position_params
        params.require(:position).permit(:title,:description,:requirements, :responsibilities)
    end
    def skill_params
        params.require(:skills_id)
    end
end

app/views/positions/_form.html.erb
<%= render  "shared/errors", obj: @position %>
<div class="row">
  <div class="col-12">
    <%= form_for @position do |f|%>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
      </div>
            <div class="form-group">
        <%= f.label :skills %><br/>
        <%= render 'shared/skill-checkbox' %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description,rows: 10,class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :requirements %>
        <%= f.text_area :requirements,rows: 10,class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :responsibilities %>
        <%= f.text_area :responsibilities,rows: 10,class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit class: "btn btn-indigo" %>
      </div>
    <% end %>
    <div class="col-12 text-center">
      <%= link_to 'Cancel and return to positions', positions_path %>
    </div>
  </div>
</div>

app/views/positions/_position-list.html.erb
<div class="row justify-content-center">
  <div class="col-12">
    <% @positions.each do |position| %>
    <div class="card mb-3">
      <div class="card-body">
        <h4><%= link_to position.title, position_path(position) %></h4>
        <%= render 'shared/skill-badges', obj: position%>
        <div class="row">
          <div class="col-8"><%= truncate(position.description, length: 200) %></div>
          <div class="col-4 text-right"><p class="lead"><%= position.candidates.count > 0 ? pluralize(position.candidates.count, "application") : "No applications"%></p></div>
        </div>
        <div class="position-meta-details">
        </div>
        <%= link_to "Edit", edit_position_path(position),class: "btn btn-sm btn-primary"  %>
        <%= link_to "Delete", position_path(position),class: "btn btn-sm btn-danger", method: :delete, data: {confirm: "Are you sure ?"}  %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/positions/edit.html.erb
<h1>Edit Position</h1>
<%= render 'form' %>

app/views/positions/index.html.erb
<h1>Positions</h1>
<p>
  <%= link_to "Create new position", new_position_path,class: "btn btn-sm btn-mdb-color" %>
</p>
<%= render 'position-list'%>

app/views/positions/new.html.erb
<h1>New Position</h1>
<%= render 'form' %>

app/views/positions/show.html.erb
<h2><%= @position.title %></h2>
<div class="mb-3"><%= render 'shared/skill-badges', obj: @position%></div>
<p><strong>Description :</strong></p>
<p><%= @position.description %></p>

<p><strong>Applied candidates :</strong></p>
<% @position.candidates.each do |candidate|%>
<%= link_to "#{candidate.first_name} #{candidate.last_name}", candidate_path(candidate),class: "btn btn-brown" %>
<% end %>