config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  resources :positions
  resources :candidates
  resources :recruiters
  resources :meetings

  # recruiter to candidate route
  post '/candidates/:id/add-recruiter/:recruiter', to: 'candidates#add_recruiter'
  delete '/candidates/:id/add-recruiter', to: 'candidates#remove_recruiter'
  
  #login/logout routes
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/candidate.rb
class Candidate < ApplicationRecord
    has_many :candidate_skill, dependent: :delete_all
    has_many :skills, through: :candidate_skill
    belongs_to :recruiter, optional: true
    belongs_to :position, optional: true
    has_many :meetings,  dependent: :destroy
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
    before_action :set_candidate, only:[:edit,:update,:show,:destroy,:add_recruiter,:remove_recruiter]
    before_action :require_user
    def index
        @candidates = Candidate.all
    end
    def show
        @recruiters = Recruiter.all
    end
    def new
        @candidate = Candidate.new
    end
    def create
        #just check if params are passing
        #render plain: params[:candidate].inspect

        @candidate = Candidate.new(candidate_params)
        if @candidate.save
            skill_params.each do |skill|
                @candidate.candidate_skill.create(skill_id:skill)
            end
            flash[:success] = "Positon was successfully created"
            redirect_to candidate_path(@candidate) 
        else
            render 'new'
        end
    end
    def edit
    end
    def update
        if @candidate.update(candidate_params)
            flash[:success] = "Candidate was successfully updated"
            redirect_to candidate_path(@candidate)    
        else
            render 'edit'
        end
        
    end
    def destroy
        @candidate.destroy
        flash[:danger] = "candidate was successfully deleted"
        redirect_to candidates_path
        
    end
    def add_recruiter
        @candidate.recruiter_id = params[:recruiter]
        if @candidate.save
            flash[:success] = "Recruiter was added to candidate"
            redirect_to candidate_path(@candidate)    
        else 
            flash[:danger] = "Holy guacamole ! there was a problem !"
            redirect_to candidate_path(@candidate)    
        end
    end
    def remove_recruiter
        @candidate.recruiter_id = nil
        @meeting = @candidate.meetings
        @candidate.meetings.delete(@meeting)
        if @candidate.save
            flash[:warning] = "Recruiter was Removed from candidate"
            redirect_to candidate_path(@candidate)    
        else 
            flash[:danger] = "Holy guacamole ! there was a problem !"
            redirect_to candidate_path(@candidate)    
        end
    end
    
    

    private
    def set_candidate
        @candidate = Candidate.find(params[:id])
    end
    def candidate_params
        params.require(:candidate).permit(:first_name,:last_name,:telephone, :email,:linked_in,:github,:position_id,:recruiter_id)
    end
    def skill_params
        params.require(:skills_id)
    end
end

app/helpers/candidates_helper.rb
module CandidatesHelper
    def sort_recruiters(recruiters,candidate)
        @sorted_recruiters = []
        @recruiters.each do |recruiter|
            matching = recruiter.skills & candidate.skills
            score = 0
            matching.each do |skill|
                if skill.skill_type == 0
                    score += 5
                elsif skill.skill_type == 1
                    score += 2
                end
            end
            @sorted_recruiters.push({score:score,recruiter:recruiter})
        end
        @sorted_recruiters.sort_by! { |r| -r[:score] }
    end
    
end

app/views/candidates/_form.html.erb
<div class="row">
  <div class="col-12">
    <%= form_for @candidate do |f|%>
      <div class="form-group">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :skills %><br/>
        <%= render 'shared/skill-checkbox' %>
      </div>
      <div class="form-group">
        <%= f.label :position_id, 'Applied for :' %><br/>
        <%= f.collection_select(:position_id, Position.all, :id, :title,{:prompt => 'Select a position...'},{class:"form-control"}) %>
      </div>
      <div class="form-group">
        <%= f.label :telephone %>
        <%= f.telephone_field :telephone, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :linked_in %>
        <%= f.text_field :linked_in, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :github %>
        <%= f.text_field :github, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit class: "btn btn-indigo" %>
      </div>
    <% end %>
    <div class="col-12 text-center">
      <%= link_to 'Cancel and return to positions', positions_path %>
    </div>
  </div>
</div>

app/views/candidates/edit.html.erb
<h1>Edit candidate</h1>
<%= render 'form'%>

app/views/candidates/index.html.erb
<h1>Candidates</h1>
<p>
  <%= link_to "Create new candidate", new_candidate_path,class: "btn btn-sm btn-mdb-color" %>
</p>
<div class="row d-flex">
  <% @candidates.each do |candidate| %>
    <div class="card mb-3 card-candidate">
        <div class="card-body">
          <h4><%= link_to "#{candidate.first_name} #{candidate.last_name}" , candidate_path(candidate) %></h4>
          <p class="lead">
            <%= candidate.position ? candidate.position.title : nil %>
          </p>
          <div class="candidate-meta-details mb-2">
             <%= render 'shared/skill-badges', obj: candidate%>
          </div>
          <%= link_to "Edit", edit_candidate_path(candidate),class: "btn btn-sm btn-primary"  %>
          <%= link_to "Delete", candidate_path(candidate),class: "btn btn-sm btn-danger", method: :delete, data: {confirm: "Are you sure ?"}  %>
        </div>
      
    </div>
  <% end %>
</div>

app/views/candidates/new.html.erb
<h1>New candidates</h1>
<%= render 'form'%>

app/views/candidates/show.html.erb
<h2><%= @candidate.first_name %> <%= @candidate.last_name %></h2>

<p class="lead">
    <%= @candidate.position ? @candidate.position.title : nil %>
</p>

<%= render 'shared/skill-badges', obj: @candidate%>

<div class="row my-4">
    <div class="col-3 text-right"><b>Name</b> :</div>
    <div class="col-9"><%= @candidate.first_name %> <%= (@candidate.last_name).upcase %></div>

    <div class="col-3 text-right"><b>Email</b> :</div>
    <div class="col-9"><%= @candidate.email %></div>

    <div class="col-3 text-right"><b>Telephone</b> :</div>
    <div class="col-9"><%= @candidate.telephone %></div>

    <div class="col-3 text-right"><b>Linked in</b> :</div>
    <div class="col-9"><%= link_to @candidate.linked_in, @candidate.linked_in, target: "_blank" %></div>

    <div class="col-3 text-right"><b>Github</b> :</div>
    <div class="col-9"><%= link_to @candidate.github, @candidate.linked_in, target: "_blank" %></div>
</div>

<div class="row">
    <div class="col">
    <%# IF Candidate has recruiter %>
        <% if @candidate.recruiter_id && @candidate.recruiter_id != 0%>
        <div class="row">
            <div class="col card">
            <div class="card-body">
            <div class="row d-flex align-items-center">
                <div class="col">
                    <h5>Recruiter :</h5>
                    <p>
                    <%= @candidate.recruiter.first_name %> <%= @candidate.recruiter.last_name %><br/>
                    <%= @candidate.recruiter.email%><br/>
                    <%= @candidate.recruiter.telephone%>
                </p>
                <%= link_to "remove", "/candidates/#{@candidate.id}/add-recruiter", :method => :delete, class: "btn btn-sm btn-danger mt-3" %>
                </div>
                <div class="col d-flex align-items-center">
                    <div>
                    <% if @candidate.meetings.length > 0 %>
                        <h5>meeting booked :</h5>
                        <p><strong>place : </strong><%= @candidate.meetings[0].place  %></p>
                        <p><strong>time : </strong><%= @candidate.meetings[0].time.strftime("%A %d %B at %H:%M")  %></p>
                        <%= link_to "cancel meeting", meeting_path(@candidate.meetings[0]), :method => :delete, class: "btn btn-sm btn-danger mt-3" %>
                    <% else %>
                        <%= link_to "Schedule a meeting", {:controller => 'meetings', :action => 'new', :id => @candidate.id }, { :class => 'btn btn-lg btn-indigo' } %>
                    <% end %>
                    </div>
                </div>
            </div>
            </div>
            </div>
        </div>
    <%# IF Candidate Doesn't have %>
        <% else %>
        <div class="row">
        <h4>Please select a recruiter :</h4>
            <% sort_recruiters(@recruiters,@candidate).each_with_index do |r, i|%>
            <div class="col-12">
                <div class="card mb-3">
                    <div class="card-body">
                        <h4><%= link_to "##{i+1} - #{r[:recruiter].first_name} #{r[:recruiter].last_name}" , recruiter_path(r[:recruiter]) %></h4>
                        <p>Match Score: <%= r[:score]%></p>
                        <%= render 'shared/skill-badges', obj: r[:recruiter]%>
                        <p class="text-center">
                            <%= link_to "Select this recruiter", "/candidates/#{@candidate.id}/add-recruiter/#{r[:recruiter].id}", :method => :post, class: "btn btn-mdb-color mt-3" %>
                        </p>
                    </div>
                </div>
            </div>
            <% end %>
        </div>
        <% end %>
    </div>
</div>