config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  resources :positions
  resources :candidates
  resources :recruiters
  resources :meetings

  # recruiter to candidate route
  post '/candidates/:id/add-recruiter/:recruiter', to: 'candidates#add_recruiter'
  delete '/candidates/:id/add-recruiter', to: 'candidates#remove_recruiter'
  
  #login/logout routes
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/recruiter.rb
class Recruiter < ApplicationRecord
    has_many :recruiter_skill, dependent: :delete_all
    has_many :skills, through: :recruiter_skill
    has_many :candidates, dependent: :nullify
    has_many :meetings,  dependent: :destroy
end

app/controllers/recruiters_controller.rb
class RecruitersController < ApplicationController
    before_action :set_recruiter, only:[:edit,:update,:show,:destroy]
    before_action :require_user
    def index
        @recruiters = Recruiter.all
    end
    def show
        
    end
    def new
        @recruiter = Recruiter.new
    end
    def create
        #just check if params are passing
        #render plain: params[:recruiter].inspect

        @recruiter = Recruiter.new(recruiter_params)
        if @recruiter.save
            skill_params.each do |skill|
                @recruiter.recruiter_skill.create(skill_id:skill)
            end
            flash[:success] = "Positon was successfully created"
            redirect_to recruiter_path(@recruiter)    
        else
            render 'new'
        end
    end
    def edit
    end
    def update
        if @recruiter.update(recruiter_params)
            flash[:success] = "Recruiter was successfully updated"
            redirect_to recruiter_path(@recruiter)    
        else
            render 'edit'
        end
        
    end
    def destroy
        @recruiter.destroy
        flash[:danger] = "recruiter was successfully deleted"
        redirect_to recruiters_path
        
    end

    private
    def set_recruiter
        @recruiter = Recruiter.find(params[:id])
    end
    def recruiter_params
        params.require(:recruiter).permit(:first_name,:last_name,:telephone, :email,:linked_in,:recruiter_id,:position_id)
    end
    def skill_params
        params.require(:skills_id)
    end
end

app/views/recruiters/_form.html.erb
<div class="row">
  <div class="col-12">
    <%= form_for @recruiter do |f|%>
      <div class="form-group">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: "form-control" %>
      </div>
            <div class="form-group">
        <%= f.label :skills %><br/>
        <%= render 'shared/skill-checkbox' %>
      </div>
      <div class="form-group">
        <%= f.label :telephone %>
        <%= f.telephone_field :telephone, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :linked_in %>
        <%= f.text_field :linked_in, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit class: "btn btn-indigo" %>
      </div>
    <% end %>
    <div class="col-12 text-center">
      <%= link_to 'Cancel and return to positions', positions_path %>
    </div>
  </div>
</div>

app/views/recruiters/edit.html.erb
<h1>Edit recruiter</h1>
<%= render 'form'%>

app/views/recruiters/index.html.erb
<h1>Recruiters</h1>
<p>
  <%= link_to "Create new recruiter", new_recruiter_path,class: "btn btn-sm btn-mdb-color" %>
</p>
<% @recruiters.each do |recruiter| %>
  <div class="card mb-3">
    <div class="card-body">
      <h4><%= link_to "#{recruiter.first_name} #{recruiter.last_name}", recruiter_path(recruiter) %></h4>
      <%= render 'shared/skill-badges', obj: recruiter%>
      <p>
        <%= recruiter.last_name %>
      </p>
      <div class="recruiter-meta-details">
      </div>
      <%= link_to "Edit", edit_recruiter_path(recruiter),class: "btn btn-sm btn-primary"  %>
      <%= link_to "Delete", recruiter_path(recruiter),class: "btn btn-sm btn-danger", method: :delete, data: {confirm: "Are you sure ?"}  %>
    </div>
  </div>
<% end %>

app/views/recruiters/new.html.erb
<h1>New recruiter</h1>
<%= render 'form'%>

app/views/recruiters/show.html.erb
<h1>Show recruiter</h1>

<h2><%= @recruiter.first_name %> <%= @recruiter.last_name %></h2>
<%= render 'shared/skill-badges', obj: @recruiter%>
<p><%= @recruiter.email %></p>