config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  resources :positions
  resources :candidates
  resources :recruiters
  resources :meetings

  # recruiter to candidate route
  post '/candidates/:id/add-recruiter/:recruiter', to: 'candidates#add_recruiter'
  delete '/candidates/:id/add-recruiter', to: 'candidates#remove_recruiter'
  
  #login/logout routes
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_messages.html.erb
<div class="row mt-3">
  <div class="col-10 offset-1">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%="#{name}"%>">
        <a href="#" class="close" data-dismis="alert">&#215</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark shadow fixed-top">
  <%= link_to "Recruit'R", root_path, class:"navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav mr-auto">
    <% if logged_in? %>
      <li class="nav-item">
        <%= link_to "Positions", positions_path, class:"nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "Candidates", candidates_path, class:"nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "Recruiters", recruiters_path, class:"nav-link"%>
      </li>
    <% end %>
    </ul>
    <ul class="navbar-nav">
    <% if logged_in? %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Profile
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to "Edit your profile", "#",class:"dropdown-item" %>
          <%= link_to "View your profile", "#",class:"dropdown-item" %>
        </div>
      </li>
      <li class="nav-item"><%= link_to 'Log out', logout_path,class:"nav-link", method: :delete %></li>
      <% else %>
      <li class="nav-item"><%= link_to 'Login', login_path, class:"nav-link" %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recruit'R</title>
    <%= favicon_link_tag asset_path('icon.png') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.10.1/css/mdb.min.css" rel="stylesheet">
    <script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js"></script>
  </head>
  <body>
    <%= render 'layouts/navigation' %>
    <div class="all">
      <%= render 'layouts/messages' %>
      <div class="container">
        <%= yield %>
      </div>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>